apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-springboot-ci
  namespace: argo
  labels:
    app: hello-springboot
spec:
  entrypoint: ci-pipeline
  arguments:
    parameters:
      - name: repo-url
        value: https://github.com/Pram821/hello-springboot.git
      - name: branch
        value: main
      - name: image
        value: pram821/hello-springboot
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 500Mi
  templates:
    - name: ci-pipeline
      steps:
        - - name: checkout
            template: checkout
        - - name: build
            template: build
        - - name: test
            template: test
        - - name: get-tag
            template: get-tag
        - - name: docker-build-push
            template: docker-build-push
            arguments:
              parameters:
                - name: tag
                  value: "{{steps.get-tag.outputs.result}}"

    - name: checkout
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args:
          - |
            git clone --branch {{workflow.parameters.branch}} {{workflow.parameters.repo-url}} /workspace/src
        volumeMounts:
          - name: workspace
            mountPath: /workspace

    - name: build
      container:
        image: maven:3.9-eclipse-temurin-17
        command: [sh, -c]
        args:
          - cd /workspace/src && mvn clean package -DskipTests
        volumeMounts:
          - name: workspace
            mountPath: /workspace

    - name: test
      container:
        image: maven:3.9-eclipse-temurin-17
        command: [sh, -c]
        args:
          - cd /workspace/src && mvn test
        volumeMounts:
          - name: workspace
            mountPath: /workspace

    - name: get-tag
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args:
          - cd /workspace/src && git rev-parse --short HEAD
        volumeMounts:
          - name: workspace
            mountPath: /workspace

    - name: docker-build-push
      inputs:
        parameters:
          - name: tag
      volumes:
        - name: docker-config
          secret:
            secretName: dockerhub-credentials
      container:
        image: gcr.io/kaniko-project/executor:latest
        args:
          - --dockerfile=/workspace/src/Dockerfile
          - --context=/workspace/src
          - --destination={{workflow.parameters.image}}:{{inputs.parameters.tag}}
          - --destination={{workflow.parameters.image}}:latest
        volumeMounts:
          - name: workspace
            mountPath: /workspace
          - name: docker-config
            mountPath: /kaniko/.docker
